### ISSUE TITLE
exports: default should be the last case

### ISSUE THREAD

**Issue by ckruse** [TN1ck/german-tax-id-validator#1]
Hi there,

since the last update I get this error:

```
Module not found: Error: Default condition should be last one
```

Apparently this is because the `default` entries in the exports should be the last entry ([here](https://github.com/TN1ck/german-tax-id-validator/blob/main/package.json#L11) and [here](https://github.com/TN1ck/german-tax-id-validator/blob/main/package.json#L15)).

Could you move the default entries down?

Best regards,
 CK

**Comment by TN1ck** [comment]
@ckruse Thanks for reporting, fixed it. Let me know if it works for you now.

**Comment by ckruse** [comment]
Problem is fixed, thank you very much :-)
